// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2vJXKyYaDASGAZt_gbAImN81XBC_N0Mo',
    appId: '1:342604250425:web:7a1ac166534f6e0c893ce8',
    messagingSenderId: '342604250425',
    projectId: 'stridezbackend',
    authDomain: 'stridezbackend.firebaseapp.com',
    storageBucket: 'stridezbackend.firebasestorage.app',
    measurementId: 'G-TJ0RBEH1E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDedw10skFMEzt4vydn9qnOjDS6V1dhRg0',
    appId: '1:342604250425:android:867f93737803b6d3893ce8',
    messagingSenderId: '342604250425',
    projectId: 'stridezbackend',
    storageBucket: 'stridezbackend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8F1p1pF6Qyzk-VAKlEFpGfWyj-RBARac',
    appId: '1:342604250425:ios:e84b232b25730191893ce8',
    messagingSenderId: '342604250425',
    projectId: 'stridezbackend',
    storageBucket: 'stridezbackend.firebasestorage.app',
    androidClientId: '342604250425-28j765bqdfp4ijotbum85sh3rloilm42.apps.googleusercontent.com',
    iosClientId: '342604250425-vkdn1rs5qf88ba0e1gso1l1otd23495t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8F1p1pF6Qyzk-VAKlEFpGfWyj-RBARac',
    appId: '1:342604250425:ios:e84b232b25730191893ce8',
    messagingSenderId: '342604250425',
    projectId: 'stridezbackend',
    storageBucket: 'stridezbackend.firebasestorage.app',
    androidClientId: '342604250425-28j765bqdfp4ijotbum85sh3rloilm42.apps.googleusercontent.com',
    iosClientId: '342604250425-vkdn1rs5qf88ba0e1gso1l1otd23495t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2vJXKyYaDASGAZt_gbAImN81XBC_N0Mo',
    appId: '1:342604250425:web:7f5fe682c2225f83893ce8',
    messagingSenderId: '342604250425',
    projectId: 'stridezbackend',
    authDomain: 'stridezbackend.firebaseapp.com',
    storageBucket: 'stridezbackend.firebasestorage.app',
    measurementId: 'G-WBGNLLDB97',
  );
}
